
[[constraint]]
  name = "github.com/Clever/pq"

[[constraint]]
  name = "github.com/kardianos/osext"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "gopkg.in/Clever/kayvee-go.v6"
  version = "6.24.0"
