routes:
  job-finished:
    matchers:
      title: [ "job-finished" ]
    output:
      type: "alerts"
      series: "job.finished"
      dimensions: [ "function", "payload" ]
      value_field: "value"
      stat_type: "gauge"
  check-latency:
    matchers:
      title: [ "check-latency" ]
    output:
      type: "alerts"
      series: "apm.latency-exceeded"
      dimensions: [ "table", "latency_threshold" ]
      value_field: "value"
      stat_type: "counter"
  check-load-errors:
    matchers:
      title: [ "check-load-errors" ]
    output:
      type: "alerts"
      series: "apm.load_errors"
      dimensions: [ "table" ]
      value_field: "value"
      stat_type: "counter"
